name: eventhandler
description: Eventhandler for Dart
version: 1.0.2
author: Daniel Íñigo Pérez <daniel.inigo.dev@gmail.com>
homepage: https://gitlab.com/daniel.inigo/dart-eventhandler

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
